### ISSUE TITLE
Need write access

### ISSUE THREAD

**Issue by schemar** [etcinit/gonduit#15]
Hey @etcinit,

you gave me access to etcinit/phabulous so that we can now merge there and make releases. Would you be so kind and give me the same rights for gonduit? I am planning on starting regular releases, bugfixes, etc. for both. Ideally, you add both repos to a "phabulous" organization and add me there, so that I could potentially add more people in the future.

Thank you for your time.

Cheers,
Martin

**Comment by schemar** [comment]
I can of course also create the organization if you are busy.

**Comment by etcinit** [comment]
I've added you as a contributor to the project. Are you the owner of github.com/phabulous?

**Comment by schemar** [comment]
No I am not the owner. And it is a valid question about go imports, I don't know if they must change. It is easier to leave it under your name. At least for now.

Thank you very much for the invite!
